export default {
  USERS: '/users',
  USER_DETAILS: '/users/details/:id',
  ANNOUNCEMENTS: '/announcements/approved',
  ANNOUNCEMENTS_PENDING: '/announcements/pending',
  ANNOUNCEMENTS_IN_REVIEW: '/announcements/in-review',
  ANNOUNCEMENTS_FEATURED: '/announcements/featured',
  ANNOUNCEMENTS_REJECTED: '/announcements/rejected',
  ANNOUNCEMENTS_EXPIRED: '/announcements/expired',
  SETTINGS: '/settings',
  REPORTS: '/reports',
  SIGNIN: '/signin',
  DASHBOARD: '/dashboard',
  PUSH_NOTIFICATIONS: '/push-notifications',
  SUPPORTS: '/supports',
  USER_ANNOUNCEMENT: '/users/details/announcement/:id',
  ANNOUNCEMENT_DETAILS: '/announcements/pending/:id',
  ANNOUNCEMENTS_DETAILS_IN_REVIEW: '/announcements/in-review/:id',
  ANNOUNCEMENT_DETAILS_APPROVED: '/announcements/approved/:id',
  ANNOUNCEMENT_DETAILS_FEATURED: '/announcements/featured/:id',
  ANNOUNCEMENT_DETAILS_REJECTED: '/announcements/rejected/:id',
  ANNOUNCEMENT_DETAILS_EXPIRED: '/announcements/expired/:id',
  ANNOUNCEMENT_DETAILS_DETAILS: '/announcements/report/:id',
  ANNOUNCEMENT_APPROVED_EDIT: '/announcements/approved/edit/:id',
  ANNOUNCEMENT_PENDING_EDIT: '/announcements/pending/edit/:id',
  ANNOUNCEMENT_IN_REVIEW_EDIT: '/announcements/in-review/edit/:id',
};